# Generated by Django 4.0.5 on 2022-06-26 21:26

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='country',
            new_name='destination_country',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='country_of_origin',
            field=django_countries.fields.CountryField(default='UG', max_length=2),
            preserve_default=False,
        ),
    ]
