# Generated by Django 4.0.5 on 2022-06-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_rename_country_shipment_destination_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='arrival_date',
            field=models.DateField(null=True, verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_date',
            field=models.DateField(null=True, verbose_name='Shipping Date'),
        ),
    ]
